#!/bin/sh

Usage()
{
    echo "usage:\tmifconfig INTERFACE ADDRESS_FAMILY ADDRESS [ROUTER]";
    echo "\tmifconfig INTERFACE inet dhcp";
    echo "\tmifconfig INTERFACE inet6 automatic";
    echo "\tmifconfig VLAN-INTERFACE create vlan VLAN-ID vlandev PHYSICAL-DEVICE";
    echo "\tmifconfig VLAN-INTERFACE destroy vlan VLAN-ID vlandev PHYSICAL-DEVICE";
    exit 0;
}

InterfaceNameResolv()
{
    en=`/usr/sbin/networksetup -listnetworkserviceorder | grep $1`;
    en=`echo ${en} | awk '{gsub(",", "", $3); print $3}'`;
    echo ${en};
}

PrintInterfaces()
{
    if [ $# = 0 ]; then
        /usr/sbin/networksetup -listnetworkserviceorder;
    else
        ifname=$1;
        en=`InterfaceNameResolv ${ifname}`;
        if [ ${en} ]; then
            /usr/sbin/networksetup -getinfo ${en};
            exit 0;
        else
            echo "mifconfig: interface ${ifname} does not exist";
            exit 1;
        fi
    fi
}

v4AddressCheck()
{
    /usr/bin/perl -e "
        my @addrs = split(/\//, \$ARGV[0]);
        if(@addrs > 2) {
            exit 1;
        }
        my @octets = split(/\./, \$addrs[0]);
        foreach my \$octet(@octets) {
            if(\$octet < 0 || \$octet > 256) {
                exit 1;
            }
        }
    " ${check_addr}
    if [ $? -eq 1 ]; then
        echo "Invalid IP Address";
        exit 1;
    fi
}

Configure_v4Address()
{
    en=`InterfaceNameResolv ${ifname}`;
    if [ $2 = "inet" ]; then
        shift
    fi
    if [ $2 = "dhcp" ]; then
        /usr/sbin/networksetup -setdhcp ${en}
        exit 0;
    fi
    addr=$2;
    mask=`echo ${addr} |
        awk -F"/" '{
            if($2 <= 0 || $2 > 32) {
                print "Invalid";
                exit 1;
            }
            prefix = int($2 / 8);
            mask = 8 - ($2 % 8);
            for(i = 1; i <= prefix; i++) {
                subnet[i] = "255";
            }
            prefix++;
            subnet[prefix] = 256 - (2^mask);
            prefix++;
            if(prefix <= 4) {
                for(i = prefix; i <= 4; i++) {
                    subnet[i] = "0";
                }
            }
            subnetmask = subnet[1] "." subnet[2] "." subnet[3] "." subnet[4];
            print subnetmask;
        }'`
    if [ "${mask}" == "Invalid" ]; then
        echo "mifconfig: Invalid Prefix";
        exit 1;
    fi
    addr=`echo ${addr} | 
        awk -F"/" '{
            print $1;
        }'`
    check_addr=$addr;
    v4AddressCheck;
    if [ "${mask}" != "0.0.0.0" ]; then
        cidr_flag=1;
        continue;
    elif [ "$3" = "netmask" -o "$3" = "mask" ]; then
        shift;
        mask=$3;
        cidr_flag=0;
    else
        mask=$3;
        cidr_flag=0;
    fi
    check_addr=$mask;
    v4AddressCheck;

    if [ $# -eq 3 -a ${cidr_flag} -eq 1 ]; then
        router=$3;
    elif [ $# -eq 4 ]; then
        router=$4;
    else
        router="None";
    fi

    if [ ${router} == "None" ]; then
        router="";
    else
        echo ${router};
        router=`echo ${router} | 
            awk -F"." '{
                if(NF > 4) {
                    print "Invalid Router Address";
                    exit 1;
                }
                for(i = 1; i <= 4; i++) {
                    if(255 <= int($i)) {
                        print "Invalid Router Address";
                        exit 1;
                    } 
                } 
                print $0;
            }'`
    fi

    /usr/sbin/networksetup -setmanual ${en} ${addr} ${mask} ${router};

    exit 0;
}

FullLength_v6Address()
{
    addr=`/usr/bin/perl -e "
        \\$v6addr = lc(@ARGV[0]);
        if(length(\\$v6addr) < 2 || length(\\$v6addr) > 39 || 
            \\$v6addr =~ /(\:\:\:)/ || \\$v6addr !~ /^[0-9a-f:]+$/) {
            exit 1;
        }
        my \\$oct_count = (() = \\$v6addr =~ /\:/g);
        if(\\$oct_count < 3 || \\$count > 7) {
            exit 1;
        }
        \\$v6addr =~ s/^::/0::/;
        \\$v6addr =~ s/::$/::0/;
        \\$v6addr =~ s/::/':0' x (8 - \\$oct_count) . ':'/e;
        \\$v6addr =~ s/[0-9a-f]+/sprintf('%04s', $&)/egi;

        if(\\$v6addr !~ /^([0-9a-f]{4}:){7}[0-9a-f]{4}$/i) {
            exit 1;
        }
        print \\"\\$v6addr\\";
        " ${check_v6addr}`;

    if [ $? -eq 1 ]; then
        echo "mifconfig: Invalid IPv6 Address";
        exit 1
    fi
}

Configure_v6Address()
{
    en=`InterfaceNameResolv ${ifname}`;
    shift;
    if [ $2 = "automatic" ]; then
        /usr/sbin/networksetup -setv6automatic ${en}
        exit 0;
    fi

    addr=$2;
    check_v6addr=${addr};
    FullLength_v6Address;

    echo "mifconfig: not implemented.";
    echo "Apple さん よろしくおねがいしまぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁす!!!!!!!!!";
    exit 0;
}

CreateVLANif()
{
    en=`InterfaceNameResolv ${ifname}`;
    if [ ${en} ]; then
        echo "mifconfig: ${ifname} exist";
        exit 1;
    fi

    if [ $3 = "vlan" ]; then
        if [ $# = 3 ]; then
            echo "Please input VLAN ID";
            exit 1;
        elif [ $4 -gt 1 -a $4 -lt 4096 ]; then
            vlanid=$4;
        else
            echo "Invalid VLAN ID";
            exit 1;
        fi
    else
        "Invalid Argument";
    fi

    if [ $5 = "vlandev" ]; then
        if [ $# = 5 ]; then
            echo "Please input VLAN device";
            exit 1;
        fi
        vlandev=$6;
        /usr/sbin/networksetup -createVLAN ${ifname} ${vlandev} ${vlanid} 
        exit 0;
    fi
}

DestroyVLANif()
{
    en=`InterfaceNameResolv ${ifname}`;
    if ! [ ${en} ]; then
        echo "mifconfig: ${ifname} does not exist";
    exit 1;
    fi

    if [ $3 = "vlan" ]; then
        if [ $# = 3 ]; then
            echo "Please input VLAN ID";
            exit 1;
        elif [ $4 -gt 1 -a $4 -lt 4096 ]; then
            vlanid=$4;
        else
            echo "Invalid VLAN ID";
            exit 1;
        fi
    else
        "Invalid Argument";
    fi

    if [ $5 = "vlandev" ]; then
        if [ $# = 5 ]; then
            echo "Please input VLAN device";
            exit 1;
        fi
        vlandev=$6;
        /usr/sbin/networksetup -deleteVLAN ${ifname} ${vlandev} ${vlanid}
        exit 0;
    fi
}

if [ $# = 0 ]; then
    PrintInterfaces
    exit 0;
fi

if [ $# = 1 ]; then
    if [ $1 = "-h" -o $1 = "--help" ]; then
        Usage
    else
        PrintInterfaces $@
    fi
fi

ifname=$1;

if [ "$2" = "create" -o "$2" = "plumb" ]; then
    CreateVLANif $@
fi

if [ "$2" = "destroy" -o "$2" = "unplumb" ]; then
    DestroyVLANif $@
fi

if [ "$2" = "inet" ]; then
    Configure_v4Address $@
elif [ "$2" = "inet6" ]; then
    Configure_v6Address $@
else
    Configure_v4Address $@
fi

exit 0
